PVObject_=pvModule
  Version=8.0.17
  Flags=$00800443

  PVObject_Commercial=pvCommercial
    Comment=www.bauer-solarenergie.de
    Flags=$0041
    Manufacturer=Bauer Solartechnik
    Model=BS-400-108M10HBB-GG
    DataSource=Manufacturer ds 2025
    YearBeg=2025
    Width=1.134
    Height=1.722
    Depth=0.030
    Weight=24.700
    NPieces=100
    PriceDate=28/10/25 13:22
    Remarks, Count=5
      Str_1=Frame: aluminium
      Str_2
      Str_3
      Str_4
      Str_5
    End of Remarks
  End of PVObject pvCommercial

  Technol=mtSiPoly
  NCelS=54
  NCelP=2
  NDiode=3
  SubModuleLayout=slTwinHalfCells
  GRef=1000
  TRef=25.0
  PNom=400.0
  PNomTolLow=0.00
  PNomTolUp=3.00
  BifacialityFactor=0.700
  Isc=13.680
  Voc=37.20
  Imp=12.840
  Vmp=31.17
  muISC=6.57
  muVocSpec=-122.8
  muPmpReq=-0.420
  RShunt=260
  Rp_0=1000
  Rp_Exp=5.50
  RSerie=0.160
  Gamma=0.978
  muGamma=-0.0011
  VMaxIEC=1500
  VMaxUL=1500
  Absorb=0.90
  ARev=3.200
  BRev=10.548
  RDiode=0.010
  VRevDiode=-0.70
  AirMassRef=1.500
  LIDLoss=3.00
  SandiaAMCorr=50.000
End of PVObject pvModule
