PVObject_=pvModule
  Version=8.0.17
  Flags=$0443

  PVObject_Commercial=pvCommercial
    Comment=www.luxor-solar.com
    Flags=$0041
    Manufacturer=Luxor
    Model=LX-400M/182-108+
    DataSource=Manufacturer ds 2025
    YearBeg=2025
    Width=1.134
    Height=1.722
    Depth=0.030
    Weight=21.500
    NPieces=100
    PriceDate=02/09/24 16:29
    Remarks, Count=5
      Str_1=Frame: Aluminium
      Str_2=Structure: Tempered glass - Tedlar
      Str_3=Connections: MC4 or equivalent
      Str_4
      Str_5
    End of Remarks
  End of PVObject pvCommercial

  Technol=mtSiMono
  NCelS=54
  NCelP=2
  NDiode=3
  SubModuleLayout=slTwinHalfCells
  GRef=1000
  TRef=25.0
  PNom=400.0
  PNomTolLow=0.00
  PNomTolUp=1.30
  BifacialityFactor=0.000
  Isc=13.570
  Voc=37.08
  Imp=12.850
  Vmp=31.14
  muISC=6.65
  muVocSpec=-111.2
  muPmpReq=-0.400
  RShunt=500
  Rp_0=2000
  Rp_Exp=5.50
  RSerie=0.142
  Gamma=0.982
  muGamma=-0.0009
  VMaxIEC=1500
  VMaxUL=1500
  Absorb=0.90
  ARev=3.200
  BRev=12.168
  RDiode=0.010
  VRevDiode=-0.70
  AirMassRef=1.500
  LIDLoss=2.50
  SandiaAMCorr=50.000
End of PVObject pvModule
