PVObject_=pvModule
  Version=8.0.17
  Flags=$00800743

  PVObject_Commercial=pvCommercial
    Comment=Axitec Energy GmbH & Co. KG  www.axitecsolar.com
    Flags=$0041
    Manufacturer=Axitec Energy
    Model=AXIbiprotect XXL HC BLK AC-400MB/108V
    DataSource=Manufacturer 2022
    YearBeg=2022
    Width=1.134
    Height=1.722
    Depth=0.030
    Weight=26.000
    NPieces=100
    PriceDate=28/10/25 12:58
    Remarks, Count=5
      Str_1=Frame: black Anodized alu frame
      Str_2=Structure: 2x2.0 mm hardened glass
      Str_3=Connections: MC4 EVO2 original
      Str_4
      Str_5
    End of Remarks
  End of PVObject pvCommercial

  Technol=mtSiMono
  NCelS=54
  NCelP=2
  NDiode=3
  SubModuleLayout=slTwinHalfCells
  FrontSurface=fsNormalGlass
  GRef=1000
  TRef=25.0
  PNom=400.0
  PNomTolLow=0.00
  PNomTolUp=1.23
  BifacialityFactor=0.700
  Isc=13.790
  Voc=37.07
  Imp=12.900
  Vmp=31.01
  muISC=6.62
  muVocSpec=-107.5
  muPmpReq=-0.350
  RShunt=240
  Rp_0=1000
  Rp_Exp=5.50
  RSerie=0.162
  Gamma=0.991
  muGamma=-0.0004
  VMaxIEC=1500
  Absorb=0.90
  ARev=3.200
  BRev=16.548
  RDiode=0.010
  VRevDiode=-0.70
  AirMassRef=1.500
  SandiaAMCorr=50.000
End of PVObject pvModule
