PVObject_=pvModule
  Version=8.0.17
  Flags=$0543

  PVObject_Commercial=pvCommercial
    Comment=www.topsun.kr (korea)
    Flags=$0041
    Manufacturer=Topsun
    Model=TS-M400
    DataSource=Manufacturer ds 2025
    YearBeg=2025
    Width=1.308
    Height=1.960
    Depth=0.040
    Weight=35.500
    NPieces=100
    PriceDate=28/10/25 13:07
    Remarks, Count=5
      Str_1=Frame: aluminium
      Str_2=Structure: Glass Tedlar
      Str_3=Connections: J Box
      Str_4
      Str_5
    End of Remarks
  End of PVObject pvCommercial

  Technol=mtSiPoly
  NCelS=96
  NCelP=1
  NDiode=4
  SubModuleLayout=slInLength
  GRef=1000
  TRef=25.0
  PNom=400.0
  PNomTolLow=0.00
  PNomTolUp=3.00
  BifacialityFactor=0.000
  Isc=8.620
  Voc=61.10
  Imp=8.120
  Vmp=49.27
  muISC=3.01
  muVocSpec=-189.4
  muPmpReq=-0.429
  RShunt=500
  Rp_0=2000
  Rp_Exp=5.50
  RSerie=0.520
  Gamma=1.011
  muGamma=-0.0004
  VMaxIEC=1000
  VMaxUL=1000
  Absorb=0.90
  ARev=3.200
  BRev=10.308
  RDiode=0.010
  VRevDiode=-0.70
  AirMassRef=1.500
  SandiaAMCorr=50.000
End of PVObject pvModule
